---
- name: restart php5.6-fpm

  systemd:
      name: php5.6-fpm
      state: restarted

- name: restart apache
  service:
    name: "{{ apache_service }}"
    state: "{{ apache_restart_state }}" 
  tags: live
